---
--- Generated by Luanalysis
--- Created by cheng.
--- DateTime: 2023/7/7 14:49
---
---
--- 这里的 KEYS[1] 就是锁的key，这里的ARGV[1] 就是当前线程标示
-- 获取锁中的标示，判断是否与当前线程标示一致
if (ARGV[1] == redis.call('get', KEYS[1])) then
    return redis.call('del', KEYS[1])
end
return 0
